{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "8120234e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 95\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c554346c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-55-355c57f9dd0e>\", line 1, in <module>\n",
      "    dex = pd.read_csv(\"pokedex_(Update_05.20).csv\")\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 610, in read_csv\n",
      "    return _read(filepath_or_buffer, kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 462, in _read\n",
      "    parser = TextFileReader(filepath_or_buffer, **kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 819, in __init__\n",
      "    self._engine = self._make_engine(self.engine)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1050, in _make_engine\n",
      "    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1867, in __init__\n",
      "    self._open_handles(src, kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1362, in _open_handles\n",
      "    self.handles = get_handle(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/common.py\", line 642, in get_handle\n",
      "    handle = open(\n",
      "OSError: [Errno 116] Stale file handle: 'pokedex_(Update_05.20).csv'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-55-355c57f9dd0e>\", line 1, in <module>\n",
      "    dex = pd.read_csv(\"pokedex_(Update_05.20).csv\")\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 610, in read_csv\n",
      "    return _read(filepath_or_buffer, kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 462, in _read\n",
      "    parser = TextFileReader(filepath_or_buffer, **kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 819, in __init__\n",
      "    self._engine = self._make_engine(self.engine)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1050, in _make_engine\n",
      "    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1867, in __init__\n",
      "    self._open_handles(src, kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1362, in _open_handles\n",
      "    self.handles = get_handle(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/common.py\", line 642, in get_handle\n",
      "    handle = open(\n",
      "OSError: [Errno 116] Stale file handle: 'pokedex_(Update_05.20).csv'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3454, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3437, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-55-355c57f9dd0e>\", line 1, in <module>\n",
      "    dex = pd.read_csv(\"pokedex_(Update_05.20).csv\")\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 610, in read_csv\n",
      "    return _read(filepath_or_buffer, kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 462, in _read\n",
      "    parser = TextFileReader(filepath_or_buffer, **kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 819, in __init__\n",
      "    self._engine = self._make_engine(self.engine)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1050, in _make_engine\n",
      "    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1867, in __init__\n",
      "    self._open_handles(src, kwds)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py\", line 1362, in _open_handles\n",
      "    self.handles = get_handle(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/pandas/io/common.py\", line 642, in get_handle\n",
      "    handle = open(\n",
      "OSError: [Errno 116] Stale file handle: 'pokedex_(Update_05.20).csv'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3454, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2940, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3165, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3376, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2063, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 737, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/opt/anaconda3/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/opt/anaconda3/lib/python3.8/posixpath.py\", line 379, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    }
   ],
   "source": [
    "dex = pd.read_csv(\"pokedex_(Update_05.20).csv\")\n",
    "dex.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "52f18148",
   "metadata": {},
   "outputs": [],
   "source": [
    "def createStats(pokeType, dex):\n",
    "    #Creates New Pokemon\n",
    "    #First, All unimportant columns are dropped\n",
    "    importantStats = dex.drop(dex.columns[[0,1,2,3,4,5,6,8,16,17,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50]\n",
    "                                         ], axis=1)\n",
    "    #Then the data is filtered based on the user-input type\n",
    "    typeStats = importantStats[importantStats[\"type_1\"] == pokeType]\n",
    "    #Making NA Values Visually Appealing\n",
    "    typeStats = typeStats.fillna(\"None\")\n",
    "    #Making New Pokemon Temporarily Be the First Pokemon of the given type\n",
    "    newPokemon = typeStats.iloc[0]\n",
    "    #Setting All Stats at Random\n",
    "    for i in range(len(newPokemon)):\n",
    "        newPokemon.iloc[i] = np.random.choice(typeStats.iloc[:,i])\n",
    "    if newPokemon['catch_rate'] == 3:\n",
    "        newPokemon['legendary_status'] = 'True'\n",
    "    else:\n",
    "        newPokemon['legendary_status'] = \"False\"\n",
    "    return newPokemon"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2d053a4c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  self._setitem_single_block(indexer, value, name)\n",
      "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:692: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  iloc._setitem_with_indexer(indexer, value, self.name)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "species             Bubble Frog Pokémon\n",
       "type_1                            Water\n",
       "type_2                             None\n",
       "height_m                            1.1\n",
       "weight_kg                          31.6\n",
       "abilities_number                      3\n",
       "ability_1                       Torrent\n",
       "ability_2                    Skill Link\n",
       "hp                                 50.0\n",
       "attack                             73.0\n",
       "defense                            68.0\n",
       "sp_attack                          80.0\n",
       "sp_defense                         63.0\n",
       "speed                              81.0\n",
       "catch_rate                         45.0\n",
       "Name: 9, dtype: object"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Testing Generation of Random Types of Pokemon\n",
    "test = createStats(np.random.choice(dex.iloc[:,9]),dex)\n",
    "test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "5038daed",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "        Unnamed: 0  pokedex_number   generation  type_number     height_m  \\\n",
      "count  1028.000000     1028.000000  1028.000000  1028.000000  1028.000000   \n",
      "mean    513.500000      437.711089     4.034047     1.527237     1.368093   \n",
      "std     296.902341      259.366480     2.234937     0.499501     3.380126   \n",
      "min       0.000000        1.000000     1.000000     1.000000     0.100000   \n",
      "25%     256.750000      213.750000     2.000000     1.000000     0.600000   \n",
      "50%     513.500000      433.500000     4.000000     2.000000     1.000000   \n",
      "75%     770.250000      663.250000     6.000000     2.000000     1.500000   \n",
      "max    1027.000000      890.000000     8.000000     2.000000   100.000000   \n",
      "\n",
      "         weight_kg  abilities_number  total_points           hp       attack  \\\n",
      "count  1027.000000       1028.000000   1028.000000  1028.000000  1028.000000   \n",
      "mean     69.753749          2.284047    437.571984    69.577821    80.119650   \n",
      "std     129.221230          0.794981    121.664910    26.385849    32.372321   \n",
      "min       0.100000          0.000000    175.000000     1.000000     5.000000   \n",
      "25%       8.800000          2.000000    330.000000    50.000000    55.000000   \n",
      "50%      28.500000          2.000000    455.000000    66.500000    76.000000   \n",
      "75%      69.100000          3.000000    510.000000    80.000000   100.000000   \n",
      "max     999.900000          3.000000   1125.000000   255.000000   190.000000   \n",
      "\n",
      "       ...  against_ground  against_flying  against_psychic  against_bug  \\\n",
      "count  ...     1028.000000     1028.000000      1028.000000  1028.000000   \n",
      "mean   ...        1.084630        1.166342         0.979329     0.992461   \n",
      "std    ...        0.784937        0.593030         0.499146     0.598301   \n",
      "min    ...        0.000000        0.250000         0.000000     0.000000   \n",
      "25%    ...        0.500000        1.000000         1.000000     0.500000   \n",
      "50%    ...        1.000000        1.000000         1.000000     1.000000   \n",
      "75%    ...        1.625000        1.000000         1.000000     1.000000   \n",
      "max    ...        4.000000        4.000000         4.000000     4.000000   \n",
      "\n",
      "       against_rock  against_ghost  against_dragon  against_dark  \\\n",
      "count   1028.000000    1028.000000     1028.000000   1028.000000   \n",
      "mean       1.239786       1.010700        0.975681      1.065661   \n",
      "std        0.699156       0.558533        0.377549      0.451054   \n",
      "min        0.250000       0.000000        0.000000      0.250000   \n",
      "25%        1.000000       1.000000        1.000000      1.000000   \n",
      "50%        1.000000       1.000000        1.000000      1.000000   \n",
      "75%        2.000000       1.000000        1.000000      1.000000   \n",
      "max        4.000000       4.000000        2.000000      4.000000   \n",
      "\n",
      "       against_steel  against_fairy  \n",
      "count    1028.000000    1028.000000  \n",
      "mean        0.980302       1.084874  \n",
      "std         0.503434       0.527743  \n",
      "min         0.000000       0.000000  \n",
      "25%         0.500000       1.000000  \n",
      "50%         1.000000       1.000000  \n",
      "75%         1.000000       1.000000  \n",
      "max         4.000000       4.000000  \n",
      "\n",
      "[8 rows x 38 columns]\n"
     ]
    }
   ],
   "source": [
    "def describePokemon(pokemon, dex):\n",
    "    tall_height = 1.5\n",
    "    short_height = 0.6\n",
    "    colors = {'Grass': [\"Green\", \"Green and White\", \"Green and Yellow\", \"Green and Purple\", \"Light Green\", \"Dark Green\", \"Emerald Green\", \"Sage Green\"],\n",
    "              'Bug': [\"Green\", \"Green and White\", \"Green and Yellow\", \"Dark Green\", \"Light Green\", \"Black and Green\", \"Neon Green\"],\n",
    "              'Fire': [\"Red\", \"Orange\", \"Red and Purple\", \"Black and Red\", \"Brown and Red\", \"Neon Pink\", \"Scarlet Red\"],\n",
    "              'Water': [\"Blue\", \"Blue and Yellow\", \"Blue and White\", \"Light Blue\", \"Ocean Blue\", \"Seafoam Green\"],\n",
    "              'Normal': [\"Grey\", \"Brown\", \"Yellow and Brown\", \"White\", \"Khaki Brown\"],\n",
    "              'Dark': [\"Dark Purple\", \"Black\", \"Light Purple\", \"Matte Black\"],\n",
    "              'Poison': [\"Dark Purple\", \"Black\", \"Light Purple\", \"Acid Green\"],\n",
    "              'Ghost': [\"Dark Purple\", \"Black\", \"Light Purple\", \"Transparent Purple\", \"Transparent Black\"],\n",
    "              'Electric': [\"Yellow and Black\", \"Yellow\", \"Orange\", \"Neon Yellow\"],\n",
    "              'Ground': [\"Dark Brown\", \"Brown\", \"Light Brown\", \"Grey\"],\n",
    "              'Rock': [\"Dark Brown\", \"Brown\", \"Light Brown\", \"Grey\"],\n",
    "              'Ice': [\"Light Blue\", \"Dark Blue\", \"White and Blue\"],\n",
    "              'Fairy': [\"Pink\", \"White and Pink\", \"Rainbow\", \"Psychadelic Pink\", \"Lavender\"],\n",
    "              'Steel': [\"Metallic Grey\", \"White\", \"Silver\", \"Grey and Red\", \"Cyan and Grey\"],\n",
    "              'Fighting': [\"Brown\", \"Orange\", \"Grey\", \"Grey and Brown\", \"Dark Blue and Fire Red\"],\n",
    "              'Psychic': [\"Yellow and Brown\", \"Pink\", \"Grey and Pink\", \"Purple\", \"Pink and Purple\"],\n",
    "              'Dragon': [\"Grey and Purple\", \"Brown and Purple\", \"Brown and Red\", \"Black and Orange\"],\n",
    "              'Flying': [\"Grey and Blue\", \"White and Blue\", \"Red and Blue\", \"Red and Grey\", \"White and Red\"]}\n",
    "    \n",
    "    if pokemon['height_m'] >= 1.5:\n",
    "        height_description = 'Tall'\n",
    "    if pokemon['height_m'] <= 0.6:\n",
    "        height_description = 'Short'\n",
    "    else:\n",
    "        height_description = 'Medium-Height'\n",
    "    \n",
    "    for key in colors:\n",
    "        if pokemon['type_1'] == key:\n",
    "            color_choice = np.random.choice(colors[key])\n",
    "    \n",
    "    pokemon[\"Desc For Image Gen\"] = str(height_description) + \" \" + str(color_choice) + \" \" + str(pokemon[\"species\"])\n",
    "    \n",
    "    print(pokemon)\n",
    "describePokemon(test, dex)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b3ee4f7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
